/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeploysRouteImport } from './routes/deploys'
import { Route as MembersRouteImport } from './routes/members'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as SpecsRouteImport } from './routes/specs'
import { Route as ValidationEngineRouteImport } from './routes/validation-engine'
import { Route as ValidationReportsRouteImport } from './routes/validation-reports'
import { Route as ValidationResultsRouteImport } from './routes/validation-results'
import { Route as SpecsSpecIdRouteImport } from './routes/specs_.$specId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploysRoute = DeploysRouteImport.update({
  id: '/deploys',
  path: '/deploys',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecsRoute = SpecsRouteImport.update({
  id: '/specs',
  path: '/specs',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidationEngineRoute = ValidationEngineRouteImport.update({
  id: '/validation-engine',
  path: '/validation-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidationReportsRoute = ValidationReportsRouteImport.update({
  id: '/validation-reports',
  path: '/validation-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidationResultsRoute = ValidationResultsRouteImport.update({
  id: '/validation-results',
  path: '/validation-results',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecsSpecIdRoute = SpecsSpecIdRouteImport.update({
  id: '/specs_/$specId',
  path: '/specs/$specId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/dashboard': typeof DashboardRoute
  '/deploys': typeof DeploysRoute
  '/members': typeof MembersRoute
  '/roles': typeof RolesRoute
  '/specs': typeof SpecsRoute
  '/validation-engine': typeof ValidationEngineRoute
  '/validation-reports': typeof ValidationReportsRoute
  '/validation-results': typeof ValidationResultsRoute
  '/specs/$specId': typeof SpecsSpecIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/dashboard': typeof DashboardRoute
  '/deploys': typeof DeploysRoute
  '/members': typeof MembersRoute
  '/roles': typeof RolesRoute
  '/specs': typeof SpecsRoute
  '/validation-engine': typeof ValidationEngineRoute
  '/validation-reports': typeof ValidationReportsRoute
  '/validation-results': typeof ValidationResultsRoute
  '/specs/$specId': typeof SpecsSpecIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/dashboard': typeof DashboardRoute
  '/deploys': typeof DeploysRoute
  '/members': typeof MembersRoute
  '/roles': typeof RolesRoute
  '/specs': typeof SpecsRoute
  '/validation-engine': typeof ValidationEngineRoute
  '/validation-reports': typeof ValidationReportsRoute
  '/validation-results': typeof ValidationResultsRoute
  '/specs_/$specId': typeof SpecsSpecIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/approvals'
    | '/dashboard'
    | '/deploys'
    | '/members'
    | '/roles'
    | '/specs'
    | '/validation-engine'
    | '/validation-reports'
    | '/validation-results'
    | '/specs/$specId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/approvals'
    | '/dashboard'
    | '/deploys'
    | '/members'
    | '/roles'
    | '/specs'
    | '/validation-engine'
    | '/validation-reports'
    | '/validation-results'
    | '/specs/$specId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/approvals'
    | '/dashboard'
    | '/deploys'
    | '/members'
    | '/roles'
    | '/specs'
    | '/validation-engine'
    | '/validation-reports'
    | '/validation-results'
    | '/specs_/$specId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  DashboardRoute: typeof DashboardRoute
  DeploysRoute: typeof DeploysRoute
  MembersRoute: typeof MembersRoute
  RolesRoute: typeof RolesRoute
  SpecsRoute: typeof SpecsRoute
  ValidationEngineRoute: typeof ValidationEngineRoute
  ValidationReportsRoute: typeof ValidationReportsRoute
  ValidationResultsRoute: typeof ValidationResultsRoute
  SpecsSpecIdRoute: typeof SpecsSpecIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploys': {
      id: '/deploys'
      path: '/deploys'
      fullPath: '/deploys'
      preLoaderRoute: typeof DeploysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specs': {
      id: '/specs'
      path: '/specs'
      fullPath: '/specs'
      preLoaderRoute: typeof SpecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validation-engine': {
      id: '/validation-engine'
      path: '/validation-engine'
      fullPath: '/validation-engine'
      preLoaderRoute: typeof ValidationEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validation-reports': {
      id: '/validation-reports'
      path: '/validation-reports'
      fullPath: '/validation-reports'
      preLoaderRoute: typeof ValidationReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validation-results': {
      id: '/validation-results'
      path: '/validation-results'
      fullPath: '/validation-results'
      preLoaderRoute: typeof ValidationResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specs_/$specId': {
      id: '/specs_/$specId'
      path: '/specs/$specId'
      fullPath: '/specs/$specId'
      preLoaderRoute: typeof SpecsSpecIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApprovalsRoute: ApprovalsRoute,
  DashboardRoute: DashboardRoute,
  DeploysRoute: DeploysRoute,
  MembersRoute: MembersRoute,
  RolesRoute: RolesRoute,
  SpecsRoute: SpecsRoute,
  ValidationEngineRoute: ValidationEngineRoute,
  ValidationReportsRoute: ValidationReportsRoute,
  ValidationResultsRoute: ValidationResultsRoute,
  SpecsSpecIdRoute: SpecsSpecIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
