-- 공용 스키마 — PostgreSQL 과 H2(PostgreSQL 모드) 양쪽에서 그대로 돈다.
-- 정본 문서는 kv 에 JSON 통째(반쯤 바뀐 정본 방지), 행 데이터는 각자 표.
-- IDENTITY 는 BIGSERIAL 대신 표준 문법 — 두 DB 공용이다.

CREATE TABLE IF NOT EXISTS kv (
  name VARCHAR(100) PRIMARY KEY,
  json TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS notices (
  id VARCHAR(20) PRIMARY KEY,
  json TEXT NOT NULL,
  created_at VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS questions (
  id VARCHAR(20) PRIMARY KEY,
  json TEXT NOT NULL,
  created_at VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_log (
  seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  json TEXT NOT NULL
);

-- 상신 접수함 — 결재 엔진은 미확정이라 접수 사실만 남긴다
CREATE TABLE IF NOT EXISTS submissions (
  seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind VARCHAR(50) NOT NULL,
  json TEXT NOT NULL,
  created_at VARCHAR(40) NOT NULL
);
